# Compare hierarchy QA histograms made by hierarchyPlots.py
# between two different versions

import argparse
import array
import math
import os
import ROOT
import sys

class parameters(object):

    def __init__(self, hFileName1, eFileName1, hFileName2, eFileName2):
        # Hierarchy histogram files
        self.hFileName1 = hFileName1
        self.eFileName1 = eFileName1
        self.hFileName2 = hFileName2
        self.eFileName2 = eFileName2

        # Max NHits & mtm (GeV/c)
        self.maxNHits = 1e4
        self.maxMtm = 5.0

def compareHistos(pars):

    # Open MC histogram ROOT file
    print('plotMCHistos using {0}, {1}, {2}, {3}'.format(pars.hFileName1, pars.eFileName1,
                                                         pars.hFileName2, pars.eFileName2))

    # Hierarchy histogram files (MC & event)
    hFile1 = ROOT.TFile.Open(pars.hFileName1, 'read')
    hFile2 = ROOT.TFile.Open(pars.hFileName2, 'read')
    eFile1 = ROOT.TFile.Open(pars.eFileName1, 'read')
    eFile2 = ROOT.TFile.Open(pars.eFileName2, 'read')

    # Define plotting canvas
    theCanvas = ROOT.TCanvas('theCanvas', '', 1350, 700)
    ROOT.gROOT.SetStyle('Plain')
    ROOT.gStyle.SetOptStat(0)
    theCanvas.UseCurrentStyle()

    # For text labelling
    text = ROOT.TLatex()
    text.SetTextSize(0.075)
    text.SetNDC(True)

    # All interactions: muons, protons, piplus, piminus, electrons & photons
    theCanvas.Divide(3,2)

    # Hits efficiency
    theCanvas.cd(1)
    h1_muHitsEff = hFile1.Get('muon_HitsEff')
    h1_muHitsEff.GetXaxis().SetRangeUser(0.0, pars.maxNHits)
    h1_muHitsEff.GetYaxis().SetRangeUser(0.0, 1.01)
    h1_muHitsEff.SetLineColor(ROOT.kBlue)
    h1_muHitsEff.SetMarkerColor(ROOT.kBlue)
    ROOT.gPad.SetLogx()
    h1_muHitsEff.Draw()
    h2_muHitsEff = hFile2.Get('muon_HitsEff')
    h2_muHitsEff.SetLineColor(ROOT.kRed)
    h2_muHitsEff.SetMarkerColor(ROOT.kRed)
    h2_muHitsEff.Draw('same')
    text.DrawLatex(0.775, 0.25, '#mu')

    theCanvas.cd(2)
    h1_pHitsEff = hFile1.Get('proton_HitsEff')
    h1_pHitsEff.GetXaxis().SetRangeUser(0.0, pars.maxNHits)
    h1_pHitsEff.GetYaxis().SetRangeUser(0.0, 1.01)
    h1_pHitsEff.SetLineColor(ROOT.kBlue)
    h1_pHitsEff.SetMarkerColor(ROOT.kBlue)
    ROOT.gPad.SetLogx()
    h1_pHitsEff.Draw()
    h2_pHitsEff = hFile2.Get('proton_HitsEff')
    h2_pHitsEff.SetLineColor(ROOT.kRed)
    h2_pHitsEff.SetMarkerColor(ROOT.kRed)
    h2_pHitsEff.Draw('same')
    text.DrawLatex(0.775, 0.25, 'p')

    theCanvas.cd(3)
    h1_eHitsEff = hFile1.Get('electron_HitsEff')
    h1_eHitsEff.GetXaxis().SetRangeUser(0.0, pars.maxNHits)
    h1_eHitsEff.GetYaxis().SetRangeUser(0.0, 1.01)
    h1_eHitsEff.SetLineColor(ROOT.kBlue)
    h1_eHitsEff.SetMarkerColor(ROOT.kBlue)
    ROOT.gPad.SetLogx()
    h1_eHitsEff.Draw()
    h2_eHitsEff = hFile2.Get('electron_HitsEff')
    h2_eHitsEff.SetLineColor(ROOT.kRed)
    h2_eHitsEff.SetMarkerColor(ROOT.kRed)
    h2_eHitsEff.Draw('same')
    text.DrawLatex(0.775, 0.25, 'e')

    theCanvas.cd(4)
    h1_pipHitsEff = hFile1.Get('piplus_HitsEff')
    h1_pipHitsEff.GetXaxis().SetRangeUser(0.0, pars.maxNHits)
    h1_pipHitsEff.GetYaxis().SetRangeUser(0.0, 1.01)
    h1_pipHitsEff.SetLineColor(ROOT.kBlue)
    h1_pipHitsEff.SetMarkerColor(ROOT.kBlue)
    ROOT.gPad.SetLogx()
    h1_pipHitsEff.Draw()
    h2_pipHitsEff = hFile2.Get('piplus_HitsEff')
    h2_pipHitsEff.SetLineColor(ROOT.kRed)
    h2_pipHitsEff.SetMarkerColor(ROOT.kRed)
    h2_pipHitsEff.Draw('same')
    text.DrawLatex(0.775, 0.25, '#pi^{+}')

    theCanvas.cd(5)
    h1_pimHitsEff = hFile1.Get('piminus_HitsEff')
    h1_pimHitsEff.GetXaxis().SetRangeUser(0.0, pars.maxNHits)
    h1_pimHitsEff.GetYaxis().SetRangeUser(0.0, 1.01)
    h1_pimHitsEff.SetLineColor(ROOT.kBlue)
    h1_pimHitsEff.SetMarkerColor(ROOT.kBlue)
    ROOT.gPad.SetLogx()
    h1_pimHitsEff.Draw()
    h2_pimHitsEff = hFile2.Get('piminus_HitsEff')
    h2_pimHitsEff.SetLineColor(ROOT.kRed)
    h2_pimHitsEff.SetMarkerColor(ROOT.kRed)
    h2_pimHitsEff.Draw('same')
    text.DrawLatex(0.775, 0.25, '#pi^{-}')

    theCanvas.cd(6)
    h1_gHitsEff = hFile1.Get('photon_HitsEff')
    h1_gHitsEff.GetXaxis().SetRangeUser(0.0, pars.maxNHits)
    h1_gHitsEff.GetYaxis().SetRangeUser(0.0, 1.01)
    h1_gHitsEff.SetLineColor(ROOT.kBlue)
    h1_gHitsEff.SetMarkerColor(ROOT.kBlue)
    ROOT.gPad.SetLogx()
    h1_gHitsEff.Draw()
    h2_gHitsEff = hFile2.Get('photon_HitsEff')
    h2_gHitsEff.SetLineColor(ROOT.kRed)
    h2_gHitsEff.SetMarkerColor(ROOT.kRed)
    h2_gHitsEff.Draw('same')
    text.DrawLatex(0.775, 0.25, '#gamma')

    theCanvas.Print('compare_allHitsEff.png')

    # Normalised hit populations (eff denominator)
    theCanvas.cd(1)
    h1_muHitsAll = hFile1.Get('muon_HitsAll')
    h1_muHitsAll.Scale(1.0/h1_muHitsAll.Integral())
    h1_muHitsAll.GetXaxis().SetRangeUser(0.0, pars.maxNHits)
    h1_muHitsAll.GetYaxis().SetTitle('Fraction of candidates')
    h1_muHitsAll.SetLineColor(ROOT.kBlue)
    h1_muHitsAll.SetMarkerColor(ROOT.kBlue)
    ROOT.gPad.SetLogx()
    h1_muHitsAll.Draw()
    h2_muHitsAll = hFile2.Get('muon_HitsAll')
    h2_muHitsAll.Scale(1.0/h2_muHitsAll.Integral())
    h2_muHitsAll.SetLineColor(ROOT.kRed)
    h2_muHitsAll.SetMarkerColor(ROOT.kRed)
    h2_muHitsAll.Draw('same')
    text.DrawLatex(0.5, 0.35, '#mu')

    theCanvas.cd(2)
    h1_pHitsAll = hFile1.Get('proton_HitsAll')
    h1_pHitsAll.Scale(1.0/h1_pHitsAll.Integral())
    h1_pHitsAll.GetYaxis().SetTitle('Fraction of candidates')
    h1_pHitsAll.GetXaxis().SetRangeUser(0.0, pars.maxNHits)
    h1_pHitsAll.SetLineColor(ROOT.kBlue)
    h1_pHitsAll.SetMarkerColor(ROOT.kBlue)
    ROOT.gPad.SetLogx()
    h1_pHitsAll.Draw()
    h2_pHitsAll = hFile2.Get('proton_HitsAll')
    h2_pHitsAll.Scale(1.0/h2_pHitsAll.Integral())
    h2_pHitsAll.SetLineColor(ROOT.kRed)
    h2_pHitsAll.SetMarkerColor(ROOT.kRed)
    h2_pHitsAll.Draw('same')
    text.DrawLatex(0.5, 0.35, 'p')

    theCanvas.cd(3)
    h1_eHitsAll = hFile1.Get('electron_HitsAll')
    h1_eHitsAll.Scale(1.0/h1_eHitsAll.Integral())
    h1_eHitsAll.GetYaxis().SetTitle('Fraction of candidates')
    h1_eHitsAll.GetXaxis().SetRangeUser(0.0, pars.maxNHits)
    h1_eHitsAll.SetLineColor(ROOT.kBlue)
    h1_eHitsAll.SetMarkerColor(ROOT.kBlue)
    ROOT.gPad.SetLogx()
    h1_eHitsAll.Draw()
    h2_eHitsAll = hFile2.Get('electron_HitsAll')
    h2_eHitsAll.Scale(1.0/h2_eHitsAll.Integral())
    h2_eHitsAll.SetLineColor(ROOT.kRed)
    h2_eHitsAll.SetMarkerColor(ROOT.kRed)
    h2_eHitsAll.Draw('same')
    text.DrawLatex(0.5, 0.35, 'e')

    theCanvas.cd(4)
    h1_pipHitsAll = hFile1.Get('piplus_HitsAll')
    h1_pipHitsAll.Scale(1.0/h1_pipHitsAll.Integral())
    h1_pipHitsAll.GetYaxis().SetTitle('Fraction of candidates')
    h1_pipHitsAll.GetXaxis().SetRangeUser(0.0, pars.maxNHits)
    h1_pipHitsAll.SetLineColor(ROOT.kBlue)
    h1_pipHitsAll.SetMarkerColor(ROOT.kBlue)
    ROOT.gPad.SetLogx()
    h1_pipHitsAll.Draw()
    h2_pipHitsAll = hFile2.Get('piplus_HitsAll')
    h2_pipHitsAll.Scale(1.0/h2_pipHitsAll.Integral())
    h2_pipHitsAll.SetLineColor(ROOT.kRed)
    h2_pipHitsAll.SetMarkerColor(ROOT.kRed)
    h2_pipHitsAll.Draw('same')
    text.DrawLatex(0.5, 0.35, '#pi^{+}')

    theCanvas.cd(5)
    h1_pimHitsAll = hFile1.Get('piminus_HitsAll')
    h1_pimHitsAll.Scale(1.0/h1_pimHitsAll.Integral())
    h1_pimHitsAll.GetYaxis().SetTitle('Fraction of candidates')
    h1_pimHitsAll.GetXaxis().SetRangeUser(0.0, pars.maxNHits)
    h1_pimHitsAll.SetLineColor(ROOT.kBlue)
    h1_pimHitsAll.SetMarkerColor(ROOT.kBlue)
    ROOT.gPad.SetLogx()
    h1_pimHitsAll.Draw()
    h2_pimHitsAll = hFile2.Get('piminus_HitsAll')
    h2_pimHitsAll.Scale(1.0/h2_pimHitsAll.Integral())
    h2_pimHitsAll.SetLineColor(ROOT.kRed)
    h2_pimHitsAll.SetMarkerColor(ROOT.kRed)
    h2_pimHitsAll.Draw('same')
    text.DrawLatex(0.5, 0.35, '#pi^{-}')

    theCanvas.cd(6)
    h1_gHitsAll = hFile1.Get('photon_HitsAll')
    h1_gHitsAll.Scale(1.0/h1_gHitsAll.Integral())
    h1_gHitsAll.GetYaxis().SetTitle('Fraction of candidates')
    h1_gHitsAll.GetXaxis().SetRangeUser(0.0, pars.maxNHits)
    h1_gHitsAll.SetLineColor(ROOT.kBlue)
    h1_gHitsAll.SetMarkerColor(ROOT.kBlue)
    ROOT.gPad.SetLogx()
    h1_gHitsAll.Draw()
    h2_gHitsAll = hFile2.Get('photon_HitsAll')
    h2_gHitsAll.Scale(1.0/h2_gHitsAll.Integral())
    h2_gHitsAll.SetLineColor(ROOT.kRed)
    h2_gHitsAll.SetMarkerColor(ROOT.kRed)
    h2_gHitsAll.Draw('same')
    text.DrawLatex(0.5, 0.35, '#gamma')

    theCanvas.Print('compare_allHits.png')

    # Momentum efficiency
    theCanvas.cd(1)
    h1_muMtmEff = hFile1.Get('muon_MtmEff')
    h1_muMtmEff.GetXaxis().SetRangeUser(0.0, pars.maxMtm)
    h1_muMtmEff.GetYaxis().SetRangeUser(0.0, 1.01)
    h1_muMtmEff.SetLineColor(ROOT.kBlue)
    h1_muMtmEff.SetMarkerColor(ROOT.kBlue)
    ROOT.gPad.SetLogx(0)
    h1_muMtmEff.Draw()
    h2_muMtmEff = hFile2.Get('muon_MtmEff')
    h2_muMtmEff.SetLineColor(ROOT.kRed)
    h2_muMtmEff.SetMarkerColor(ROOT.kRed)
    h2_muMtmEff.Draw('same')
    text.DrawLatex(0.775, 0.25, '#mu')

    theCanvas.cd(2)
    h1_pMtmEff = hFile1.Get('proton_MtmEff')
    h1_pMtmEff.GetXaxis().SetRangeUser(0.0, pars.maxMtm)
    h1_pMtmEff.GetYaxis().SetRangeUser(0.0, 1.01)
    h1_pMtmEff.SetLineColor(ROOT.kBlue)
    h1_pMtmEff.SetMarkerColor(ROOT.kBlue)
    ROOT.gPad.SetLogx(0)
    h1_pMtmEff.Draw()
    h2_pMtmEff = hFile2.Get('proton_MtmEff')
    h2_pMtmEff.SetLineColor(ROOT.kRed)
    h2_pMtmEff.SetMarkerColor(ROOT.kRed)
    h2_pMtmEff.Draw('same')
    text.DrawLatex(0.775, 0.25, 'p')

    theCanvas.cd(3)
    h1_eMtmEff = hFile1.Get('electron_MtmEff')
    h1_eMtmEff.GetXaxis().SetRangeUser(0.0, pars.maxMtm)
    h1_eMtmEff.GetYaxis().SetRangeUser(0.0, 1.01)
    h1_eMtmEff.SetLineColor(ROOT.kBlue)
    h1_eMtmEff.SetMarkerColor(ROOT.kBlue)
    ROOT.gPad.SetLogx(0)
    h1_eMtmEff.Draw()
    h2_eMtmEff = hFile2.Get('electron_MtmEff')
    h2_eMtmEff.SetLineColor(ROOT.kRed)
    h2_eMtmEff.SetMarkerColor(ROOT.kRed)
    h2_eMtmEff.Draw('same')
    text.DrawLatex(0.775, 0.25, 'e')

    theCanvas.cd(4)
    h1_pipMtmEff = hFile1.Get('piplus_MtmEff')
    h1_pipMtmEff.GetXaxis().SetRangeUser(0.0, pars.maxMtm)
    h1_pipMtmEff.GetYaxis().SetRangeUser(0.0, 1.01)
    h1_pipMtmEff.SetLineColor(ROOT.kBlue)
    h1_pipMtmEff.SetMarkerColor(ROOT.kBlue)
    ROOT.gPad.SetLogx(0)
    h1_pipMtmEff.Draw()
    h2_pipMtmEff = hFile2.Get('piplus_MtmEff')
    h2_pipMtmEff.SetLineColor(ROOT.kRed)
    h2_pipMtmEff.SetMarkerColor(ROOT.kRed)
    h2_pipMtmEff.Draw('same')
    text.DrawLatex(0.775, 0.25, '#pi^{+}')

    theCanvas.cd(5)
    h1_pimMtmEff = hFile1.Get('piminus_MtmEff')
    h1_pimMtmEff.GetXaxis().SetRangeUser(0.0, pars.maxMtm)
    h1_pimMtmEff.GetYaxis().SetRangeUser(0.0, 1.01)
    h1_pimMtmEff.SetLineColor(ROOT.kBlue)
    h1_pimMtmEff.SetMarkerColor(ROOT.kBlue)
    ROOT.gPad.SetLogx(0)
    h1_pimMtmEff.Draw()
    h2_pimMtmEff = hFile2.Get('piminus_MtmEff')
    h2_pimMtmEff.SetLineColor(ROOT.kRed)
    h2_pimMtmEff.SetMarkerColor(ROOT.kRed)
    h2_pimMtmEff.Draw('same')
    text.DrawLatex(0.775, 0.25, '#pi^{-}')

    theCanvas.cd(6)
    h1_gMtmEff = hFile1.Get('photon_MtmEff')
    h1_gMtmEff.GetXaxis().SetRangeUser(0.0, pars.maxMtm)
    h1_gMtmEff.GetYaxis().SetRangeUser(0.0, 1.01)
    h1_gMtmEff.SetLineColor(ROOT.kBlue)
    h1_gMtmEff.SetMarkerColor(ROOT.kBlue)
    ROOT.gPad.SetLogx(0)
    h1_gMtmEff.Draw()
    h2_gMtmEff = hFile2.Get('photon_MtmEff')
    h2_gMtmEff.SetLineColor(ROOT.kRed)
    h2_gMtmEff.SetMarkerColor(ROOT.kRed)
    h2_gMtmEff.Draw('same')
    text.DrawLatex(0.775, 0.25, '#gamma')

    theCanvas.Print('compare_allMtmEff.png')

    # Momentum populations (eff denominator)
    theCanvas.cd(1)
    h1_muMtmAll = hFile1.Get('muon_MtmAll')
    h1_muMtmAll.Scale(1.0/h1_muMtmAll.Integral())
    h1_muMtmAll.GetYaxis().SetTitle('Fraction of candidates')
    h1_muMtmAll.GetXaxis().SetRangeUser(0.0, pars.maxMtm)
    h1_muMtmAll.SetLineColor(ROOT.kBlue)
    h1_muMtmAll.SetMarkerColor(ROOT.kBlue)
    ROOT.gPad.SetLogx(0)
    h1_muMtmAll.Draw()
    h2_muMtmAll = hFile2.Get('muon_MtmAll')
    h2_muMtmAll.Scale(1.0/h2_muMtmAll.Integral())
    h2_muMtmAll.SetLineColor(ROOT.kRed)
    h2_muMtmAll.SetMarkerColor(ROOT.kRed)
    h2_muMtmAll.Draw('same')
    text.DrawLatex(0.775, 0.25, '#mu')

    theCanvas.cd(2)
    h1_pMtmAll = hFile1.Get('proton_MtmAll')
    h1_pMtmAll.Scale(1.0/h1_pMtmAll.Integral())
    h1_pMtmAll.GetYaxis().SetTitle('Fraction of candidates')
    h1_pMtmAll.GetXaxis().SetRangeUser(0.0, pars.maxMtm)
    h1_pMtmAll.SetLineColor(ROOT.kBlue)
    h1_pMtmAll.SetMarkerColor(ROOT.kBlue)
    ROOT.gPad.SetLogx(0)
    h1_pMtmAll.Draw()
    h2_pMtmAll = hFile2.Get('proton_MtmAll')
    h2_pMtmAll.Scale(1.0/h2_pMtmAll.Integral())
    h2_pMtmAll.SetLineColor(ROOT.kRed)
    h2_pMtmAll.SetMarkerColor(ROOT.kRed)
    h2_pMtmAll.Draw('same')
    text.DrawLatex(0.775, 0.25, 'p')

    theCanvas.cd(3)
    h1_eMtmAll = hFile1.Get('electron_MtmAll')
    h1_eMtmAll.Scale(1.0/h1_eMtmAll.Integral())
    h1_eMtmAll.GetYaxis().SetTitle('Fraction of candidates')
    h1_eMtmAll.GetXaxis().SetRangeUser(0.0, pars.maxMtm)
    h1_eMtmAll.SetLineColor(ROOT.kBlue)
    h1_eMtmAll.SetMarkerColor(ROOT.kBlue)
    ROOT.gPad.SetLogx(0)
    h1_eMtmAll.Draw()
    h2_eMtmAll = hFile2.Get('electron_MtmAll')
    h2_eMtmAll.Scale(1.0/h2_eMtmAll.Integral())
    h2_eMtmAll.SetLineColor(ROOT.kRed)
    h2_eMtmAll.SetMarkerColor(ROOT.kRed)
    h2_eMtmAll.Draw('same')
    text.DrawLatex(0.775, 0.25, 'e')

    theCanvas.cd(4)
    h1_pipMtmAll = hFile1.Get('piplus_MtmAll')
    h1_pipMtmAll.Scale(1.0/h1_pipMtmAll.Integral())
    h1_pipMtmAll.GetYaxis().SetTitle('Fraction of candidates')
    h1_pipMtmAll.GetXaxis().SetRangeUser(0.0, pars.maxMtm)
    h1_pipMtmAll.SetLineColor(ROOT.kBlue)
    h1_pipMtmAll.SetMarkerColor(ROOT.kBlue)
    ROOT.gPad.SetLogx(0)
    h1_pipMtmAll.Draw()
    h2_pipMtmAll = hFile2.Get('piplus_MtmAll')
    h2_pipMtmAll.Scale(1.0/h2_pipMtmAll.Integral())
    h2_pipMtmAll.SetLineColor(ROOT.kRed)
    h2_pipMtmAll.SetMarkerColor(ROOT.kRed)
    h2_pipMtmAll.Draw('same')
    text.DrawLatex(0.775, 0.25, '#pi^{+}')

    theCanvas.cd(5)
    h1_pimMtmAll = hFile1.Get('piminus_MtmAll')
    h1_pimMtmAll.Scale(1.0/h1_pimMtmAll.Integral())
    h1_pimMtmAll.GetYaxis().SetTitle('Fraction of candidates')
    h1_pimMtmAll.GetXaxis().SetRangeUser(0.0, pars.maxMtm)
    h1_pimMtmAll.SetLineColor(ROOT.kBlue)
    h1_pimMtmAll.SetMarkerColor(ROOT.kBlue)
    ROOT.gPad.SetLogx(0)
    h1_pimMtmAll.Draw()
    h2_pimMtmAll = hFile2.Get('piminus_MtmAll')
    h2_pimMtmAll.Scale(1.0/h2_pimMtmAll.Integral())
    h2_pimMtmAll.SetLineColor(ROOT.kRed)
    h2_pimMtmAll.SetMarkerColor(ROOT.kRed)
    h2_pimMtmAll.Draw('same')
    text.DrawLatex(0.775, 0.25, '#pi^{-}')

    theCanvas.cd(6)
    h1_gMtmAll = hFile1.Get('photon_MtmAll')
    h1_gMtmAll.Scale(1.0/h1_gMtmAll.Integral())
    h1_gMtmAll.GetYaxis().SetTitle('Fraction of candidates')
    h1_gMtmAll.GetXaxis().SetRangeUser(0.0, pars.maxMtm)
    h1_gMtmAll.SetLineColor(ROOT.kBlue)
    h1_gMtmAll.SetMarkerColor(ROOT.kBlue)
    ROOT.gPad.SetLogx(0)
    h1_gMtmAll.Draw()
    h2_gMtmAll = hFile2.Get('photon_MtmAll')
    h2_gMtmAll.Scale(1.0/h2_gMtmAll.Integral())
    h2_gMtmAll.SetLineColor(ROOT.kRed)
    h2_gMtmAll.SetMarkerColor(ROOT.kRed)
    h2_gMtmAll.Draw('same')
    text.DrawLatex(0.775, 0.25, '#gamma')

    theCanvas.Print('compare_allMtm.png')

    # Vertexing: normalise histos
    theCanvas2 = ROOT.TCanvas('theCanvas2', '', 900, 700)
    theCanvas2.UseCurrentStyle()
    theCanvas2.Divide(2,2)

    theCanvas2.cd(1)
    h1_allVtxDX = eFile1.Get('allVtxDX')
    h1_allVtxDX.GetYaxis().SetTitle('')
    h1_allVtxDX.Scale(1.0/h1_allVtxDX.Integral())
    h1_allVtxDX.SetLineColor(ROOT.kBlue)
    h1_allVtxDX.SetMarkerColor(ROOT.kBlue)
    h1_allVtxDX.Draw()
    h2_allVtxDX = eFile2.Get('allVtxDX')
    h2_allVtxDX.GetYaxis().SetTitle('')
    h2_allVtxDX.Scale(1.0/h2_allVtxDX.Integral())
    h2_allVtxDX.SetLineColor(ROOT.kRed)
    h2_allVtxDX.SetMarkerColor(ROOT.kRed)
    h2_allVtxDX.Draw('same')

    theCanvas2.cd(2)
    h1_allVtxDY = eFile1.Get('allVtxDY')
    h1_allVtxDY.Scale(1.0/h1_allVtxDY.Integral())
    h1_allVtxDY.GetYaxis().SetTitle('')
    h1_allVtxDY.SetLineColor(ROOT.kBlue)
    h1_allVtxDY.SetMarkerColor(ROOT.kBlue)
    h1_allVtxDY.Draw()
    h2_allVtxDY = eFile2.Get('allVtxDY')
    h2_allVtxDY.Scale(1.0/h2_allVtxDY.Integral())
    h2_allVtxDY.GetYaxis().SetTitle('')    
    h2_allVtxDY.SetLineColor(ROOT.kRed)
    h2_allVtxDY.SetMarkerColor(ROOT.kRed)
    h2_allVtxDY.Draw('same')

    theCanvas2.cd(3)
    h1_allVtxDZ = eFile1.Get('allVtxDZ')
    h1_allVtxDZ.Scale(1.0/h1_allVtxDZ.Integral())
    h1_allVtxDZ.GetYaxis().SetTitle('')
    h1_allVtxDZ.SetLineColor(ROOT.kBlue)
    h1_allVtxDZ.SetMarkerColor(ROOT.kBlue)
    h1_allVtxDZ.Draw()
    h2_allVtxDZ = eFile2.Get('allVtxDZ')
    h2_allVtxDZ.Scale(1.0/h2_allVtxDZ.Integral())
    h2_allVtxDZ.GetYaxis().SetTitle('')
    h2_allVtxDZ.SetLineColor(ROOT.kRed)
    h2_allVtxDZ.SetMarkerColor(ROOT.kRed)
    h2_allVtxDZ.Draw('same')

    theCanvas2.cd(4)
    h1_allVtxDR = eFile1.Get('allVtxDR')
    h1_allVtxDR.Scale(1.0/h1_allVtxDR.Integral())
    h1_allVtxDR.GetYaxis().SetTitle('')
    h1_allVtxDR.SetLineColor(ROOT.kBlue)
    h1_allVtxDR.SetMarkerColor(ROOT.kBlue)
    h1_allVtxDR.Draw()
    h2_allVtxDR = eFile2.Get('allVtxDR')
    h2_allVtxDR.Scale(1.0/h2_allVtxDR.Integral())
    h2_allVtxDR.GetYaxis().SetTitle('')
    h2_allVtxDR.SetLineColor(ROOT.kRed)
    h2_allVtxDR.SetMarkerColor(ROOT.kRed)
    h2_allVtxDR.Draw('same')

    theCanvas2.Print('compare_allVtx.png')

    # Negative drift vertex residuals
    theCanvas2.cd(1)
    h1_negVtxDX = eFile1.Get('negVtxDX')
    h1_negVtxDX.GetYaxis().SetTitle('')
    h1_negVtxDX.Scale(1.0/h1_negVtxDX.Integral())
    h1_negVtxDX.SetLineColor(ROOT.kBlue)
    h1_negVtxDX.SetMarkerColor(ROOT.kBlue)
    h1_negVtxDX.Draw()
    h2_negVtxDX = eFile2.Get('negVtxDX')
    h2_negVtxDX.GetYaxis().SetTitle('')
    h2_negVtxDX.Scale(1.0/h2_negVtxDX.Integral())
    h2_negVtxDX.SetLineColor(ROOT.kRed)
    h2_negVtxDX.SetMarkerColor(ROOT.kRed)
    h2_negVtxDX.Draw('same')

    theCanvas2.cd(2)
    h1_negVtxDY = eFile1.Get('negVtxDY')
    h1_negVtxDY.Scale(1.0/h1_negVtxDY.Integral())
    h1_negVtxDY.GetYaxis().SetTitle('')
    h1_negVtxDY.SetLineColor(ROOT.kBlue)
    h1_negVtxDY.SetMarkerColor(ROOT.kBlue)
    h1_negVtxDY.Draw()
    h2_negVtxDY = eFile2.Get('negVtxDY')
    h2_negVtxDY.Scale(1.0/h2_negVtxDY.Integral())
    h2_negVtxDY.GetYaxis().SetTitle('')
    h2_negVtxDY.SetLineColor(ROOT.kRed)
    h2_negVtxDY.SetMarkerColor(ROOT.kRed)
    h2_negVtxDY.Draw('same')

    theCanvas2.cd(3)
    h1_negVtxDZ = eFile1.Get('negVtxDZ')
    h1_negVtxDZ.Scale(1.0/h1_negVtxDZ.Integral())
    h1_negVtxDZ.GetYaxis().SetTitle('')
    h1_negVtxDZ.SetLineColor(ROOT.kBlue)
    h1_negVtxDZ.SetMarkerColor(ROOT.kBlue)
    h1_negVtxDZ.Draw()
    h2_negVtxDZ = eFile2.Get('negVtxDZ')
    h2_negVtxDZ.Scale(1.0/h2_negVtxDZ.Integral())
    h2_negVtxDZ.GetYaxis().SetTitle('')
    h2_negVtxDZ.SetLineColor(ROOT.kRed)
    h2_negVtxDZ.SetMarkerColor(ROOT.kRed)
    h2_negVtxDZ.Draw('same')

    theCanvas2.cd(4)
    h1_negVtxDR = eFile1.Get('negVtxDR')
    h1_negVtxDR.Scale(1.0/h1_negVtxDR.Integral())
    h1_negVtxDR.GetYaxis().SetTitle('')
    h1_negVtxDR.SetLineColor(ROOT.kBlue)
    h1_negVtxDR.SetMarkerColor(ROOT.kBlue)
    h1_negVtxDR.Draw()
    h2_negVtxDR = eFile2.Get('negVtxDR')
    h2_negVtxDR.Scale(1.0/h2_negVtxDR.Integral())
    h2_negVtxDR.GetYaxis().SetTitle('')
    h2_negVtxDR.SetLineColor(ROOT.kRed)
    h2_negVtxDR.SetMarkerColor(ROOT.kRed)
    h2_negVtxDR.Draw('same')

    theCanvas2.Print('compare_negVtx.png')

    # Positive drift vertex residuals
    theCanvas2.cd(1)
    h1_posVtxDX = eFile1.Get('posVtxDX')
    h1_posVtxDX.GetYaxis().SetTitle('')
    h1_posVtxDX.Scale(1.0/h1_posVtxDX.Integral())
    h1_posVtxDX.SetLineColor(ROOT.kBlue)
    h1_posVtxDX.SetMarkerColor(ROOT.kBlue)
    h1_posVtxDX.Draw()
    h2_posVtxDX = eFile2.Get('posVtxDX')
    h2_posVtxDX.GetYaxis().SetTitle('')
    h2_posVtxDX.Scale(1.0/h2_posVtxDX.Integral())
    h2_posVtxDX.SetLineColor(ROOT.kRed)
    h2_posVtxDX.SetMarkerColor(ROOT.kRed)
    h2_posVtxDX.Draw('same')

    theCanvas2.cd(2)
    h1_posVtxDY = eFile1.Get('posVtxDY')
    h1_posVtxDY.Scale(1.0/h1_posVtxDY.Integral())
    h1_posVtxDY.GetYaxis().SetTitle('')
    h1_posVtxDY.SetLineColor(ROOT.kBlue)
    h1_posVtxDY.SetMarkerColor(ROOT.kBlue)
    h1_posVtxDY.Draw()
    h2_posVtxDY = eFile2.Get('posVtxDY')
    h2_posVtxDY.Scale(1.0/h2_posVtxDY.Integral())
    h2_posVtxDY.GetYaxis().SetTitle('')
    h2_posVtxDY.SetLineColor(ROOT.kRed)
    h2_posVtxDY.SetMarkerColor(ROOT.kRed)
    h2_posVtxDY.Draw('same')

    theCanvas2.cd(3)
    h1_posVtxDZ = eFile1.Get('posVtxDZ')
    h1_posVtxDZ.Scale(1.0/h1_posVtxDZ.Integral())
    h1_posVtxDZ.GetYaxis().SetTitle('')
    h1_posVtxDZ.SetLineColor(ROOT.kBlue)
    h1_posVtxDZ.SetMarkerColor(ROOT.kBlue)
    h1_posVtxDZ.Draw()
    h2_posVtxDZ = eFile2.Get('posVtxDZ')
    h2_posVtxDZ.Scale(1.0/h2_posVtxDZ.Integral())
    h2_posVtxDZ.GetYaxis().SetTitle('')
    h2_posVtxDZ.SetLineColor(ROOT.kRed)
    h2_posVtxDZ.SetMarkerColor(ROOT.kRed)
    h2_posVtxDZ.Draw('same')

    theCanvas2.cd(4)
    h1_posVtxDR = eFile1.Get('posVtxDR')
    h1_posVtxDR.Scale(1.0/h1_posVtxDR.Integral())
    h1_posVtxDR.GetYaxis().SetTitle('')
    h1_posVtxDR.SetLineColor(ROOT.kBlue)
    h1_posVtxDR.SetMarkerColor(ROOT.kBlue)
    h1_posVtxDR.Draw()
    h2_posVtxDR = eFile2.Get('posVtxDR')
    h2_posVtxDR.Scale(1.0/h2_posVtxDR.Integral())
    h2_posVtxDR.GetYaxis().SetTitle('')
    h2_posVtxDR.SetLineColor(ROOT.kRed)
    h2_posVtxDR.SetMarkerColor(ROOT.kRed)
    h2_posVtxDR.Draw('same')

    theCanvas2.Print('compare_posVtx.png')

    # Close the histogram files
    hFile1.Close()
    hFile2.Close()
    eFile1.Close()
    eFile2.Close()


def run(args):

    pars = parameters(args.hFileName1, args.eFileName1, args.hFileName2, args.eFileName2)

    # Plot the comparisons
    compareHistos(pars)


def processArgs(parser):

    # Process script arguments
    parser.add_argument('--hFileName1', default='MCHierarchy_Histos1.root', metavar='fileName',
                        help='1st MC hierarchy histogram ROOT file [default "MCHierarchy_Histos1.root"]')

    parser.add_argument('--eFileName1', default='EventHierarchy_Histos1.root', metavar='fileName',
                        help='1st event hierarchy histogram ROOT file [default "EventHierarchy_Histos1.root"]')

    parser.add_argument('--hFileName2', default='MCHierarchy_Histos2.root', metavar='fileName',
                        help='2nd MC hierarchy histogram ROOT file [default "MCHierarchy_Histos2.root"]')

    parser.add_argument('--eFileName2', default='EventHierarchy_Histos2.root', metavar='fileName',
                        help='2nd event hierarchy histogram ROOT file [default "EventHierarchy_Histos2.root"]')


if __name__ == '__main__':

    # Process the command line arguments
    # Use "python hierarchyPlots.py --help" to see the full list
    parser = argparse.ArgumentParser(description='List of arguments')
    processArgs(parser)
    args = parser.parse_args()

    run(args)
